import React from "react";
import LoginForm from "../components/account/LoginForm";
import { render, fireEvent } from "@testing-library/react-native";
import { NavigationContainer } from "@react-navigation/native";

      // Renders the login form with email and password inputs and a login button
     // Generated by CodiumAI

describe('LoginForm', () => {

    // Renders the login form with email and password inputs and a login button
    it('should render the login form with email and password inputs and a login button', () => {
      const { getByPlaceholderText, getByText } = render(
        <NavigationContainer>
          <LoginForm />
        </NavigationContainer>
      );
      const emailInput = getByPlaceholderText("Correo Electrónico");
      const passwordInput = getByPlaceholderText("Contraseña");
      const loginButton = getByText("Iniciar Sesión");

      expect(emailInput).toBeTruthy();
      expect(passwordInput).toBeTruthy();
      expect(loginButton).toBeTruthy();
    });

    // Allows the user to input their email and password
    it('should allow the user to input their email and password', () => {
      const { getByPlaceholderText } = render(
        <NavigationContainer>
          <LoginForm />
        </NavigationContainer>
      );
      const emailInput = getByPlaceholderText("Correo Electrónico");
      const passwordInput = getByPlaceholderText("Contraseña");

      fireEvent.changeText(emailInput, "test@example.com");
      fireEvent.changeText(passwordInput, "password123");

      expect(emailInput.props.value).toBe("test@example.com");
      expect(passwordInput.props.value).toBe("password123");
    });

    // Validates the email and password inputs
    it('should validate the email and password inputs', () => {
      const { getByPlaceholderText, getByText } = render(
        <NavigationContainer>
          <LoginForm />
        </NavigationContainer>
      );
      const emailInput = getByPlaceholderText("Correo Electrónico");
      const passwordInput = getByPlaceholderText("Contraseña");
      const loginButton = getByText("Iniciar Sesión");

      fireEvent.changeText(emailInput, "invalidemail");
      fireEvent.changeText(passwordInput, "");

      fireEvent.press(loginButton);

      const emailError = getByText("Debes de ingresar un email válido.");
      const passwordError = getByText("Debes de ingresar tu contraseña.");

      expect(emailError).toBeTruthy();
      expect(passwordError).toBeTruthy();
    });

    // Displays an error message if the login request fails
    it('should display an error message if the login request fails', async () => {
      axios.post.mockRejectedValueOnce(new Error("Login failed"));

      const { getByPlaceholderText, getByText } = render(
        <NavigationContainer>
          <LoginForm />
        </NavigationContainer>
      );
      const emailInput = getByPlaceholderText("Correo Electrónico");
      const passwordInput = getByPlaceholderText("Contraseña");
      const loginButton = getByText("Iniciar Sesión");

      fireEvent.changeText(emailInput, "test@example.com");
      fireEvent.changeText(passwordInput, "password123");

      await fireEvent.press(loginButton);

      const errorMessage = getByText("Login failed");

      expect(errorMessage).toBeTruthy();
    });

    // Does not allow the user to submit the form if the email or password inputs are empty
    it('should not allow the user to submit the form if the email or password inputs are empty', () => {
      const { getByPlaceholderText, getByText } = render(
        <NavigationContainer>
          <LoginForm />
        </NavigationContainer>
      );
      const emailInput = getByPlaceholderText("Correo Electrónico");
      const passwordInput = getByPlaceholderText("Contraseña");
      const loginButton = getByText("Iniciar Sesión");

      fireEvent.changeText(emailInput, "");
      fireEvent.changeText(passwordInput, "");

      fireEvent.press(loginButton);

      const emailError = getByText("Debes de ingresar un email válido.");
      const passwordError = getByText("Debes de ingresar tu contraseña.");

      expect(emailError).toBeTruthy();
      expect(passwordError).toBeTruthy();
    });

    // Does not allow the user to submit the form if the email input is not a valid email address
    it('should not allow the user to submit the form if the email input is not a valid email address', () => {
      const { getByPlaceholderText, getByText } = render(
        <NavigationContainer>
          <LoginForm />
        </NavigationContainer>
      );
      const emailInput = getByPlaceholderText("Correo Electrónico");
      const passwordInput = getByPlaceholderText("Contraseña");
      const loginButton = getByText("Iniciar Sesión");

      fireEvent.changeText(emailInput, "invalidemail");
      fireEvent.changeText(passwordInput, "password123");

      fireEvent.press(loginButton);

      const emailError = getByText("Debes de ingresar un email válido.");

      expect(emailError).toBeTruthy();
    });
});

